### ISSUE TITLE
Lot's of issues

### ISSUE THREAD

**Issue by Anydex** [Lec1erc/Telegram_creator_GUI#1]
This does not work properly, please fix it.

**Comment by Lec1erc** [comment]
This works fine. Can you show the bug?

**Comment by Anydex** [comment]
after receiving the code, an error pops up and the account is not made.

**Comment by lonakan** [comment]
The authentication code will not be sent. The send_code_request part of the telethon does not work. Can I contact you through Telegram? @lonakan

**Comment by diraygok** [comment]
> The authentication code will not be sent. The send_code_request part of the telethon does not work. Can I contact you through Telegram? @lonakan

I have same problem

**Comment by Lec1erc** [comment]
Probably API links for your service is broken. Can you tell, which service are you using?

**Comment by diraygok** [comment]
> Probably API links for your service is broken. Can you tell, which service are you using?


Could you create accounts without any problems right now? There is a problem on my setup about sending code about two days. I'm using sms-activate API.
